language: node_js

sudo: required

os:
  - linux
  - osx
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
env:
  - BUILD_TASK=test 
  - BUILD_TASK=prebuild

matrix:
  include:
    - os: linux
      node_js: 12
      env:
        - TARGET=4.0.0
        - BUILD_TASK=prebuild
        - RUNTIME=electron
    - os: linux
      node_js: 12
      env:
        - TARGET=4.0.4
        - BUILD_TASK=prebuild
        - RUNTIME=electron
    - os: linux
      node_js: 12
      env:
        - TARGET=5.0.0
        - BUILD_TASK=prebuild
        - RUNTIME=electron
    - os: linux
      node_js: 12
      env:
        - TARGET=6.0.0
        - BUILD_TASK=prebuild
        - RUNTIME=electron
    - os: linux
      node_js: 12
      env:
        - TARGET=7.0.0
        - BUILD_TASK=prebuild
        - RUNTIME=electron
    - os: linux
      node_js: 12
      env:
        - TARGET=8.0.0
        - BUILD_TASK=prebuild
        - RUNTIME=electron
    - os: osx
      node_js: 12
      env:
        - TARGET=4.0.0
        - BUILD_TASK=prebuild
        - RUNTIME=electron
    - os: osx
      node_js: 12
      env:
        - TARGET=4.0.4
        - BUILD_TASK=prebuild
        - RUNTIME=electron
    - os: osx
      node_js: 12
      env:
        - TARGET=5.0.0
        - BUILD_TASK=prebuild
        - RUNTIME=electron
    - os: osx
      node_js: 12
      env:
        - TARGET=6.0.0
        - BUILD_TASK=prebuild
        - RUNTIME=electron
    - os: osx
      node_js: 12
      env:
        - TARGET=7.0.0
        - BUILD_TASK=prebuild
        - RUNTIME=electron
    - os: osx
      node_js: 12
      env:
        - TARGET=8.0.0
        - BUILD_TASK=prebuild
        - RUNTIME=electron

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    chmod +x ./ci/$BUILD_TASK/$BUILD_TASK.sh;
    fi

install: true

script:
  - if [[ $BUILD_TASK != "prebuild" ]]; then
    sh ./ci/test/script/run-test.sh;
    fi
  - if [[ $BUILD_TASK == "prebuild" && $TRAVIS_TAG != "" ]]; then
    cd ./ci/$BUILD_TASK;
    npm run $BUILD_TASK $TARGET $RUNTIME;
    fi
